public enum ConfigTypes
{
  AUTHOR,
  TITLE,
  GITHUB,
  PREFABS_PATH,
  SPRITES_PATH,
  MUSIC_PATH,
  SFX_PATH,
  RANKING_PATH,
  TILESET_NAME,
  DIFFICULTY,
  PREFAB_CELL,
  PREFAB_SFX_AUDIO_SOURCE,
  PREFAB_MUSIC_AUDIO_SOURCE,
  DATE_FORMAT,
  SCREENSHOT_EXTENSION,
}